### ISSUE TITLE
Include regional level data in EDA

### ISSUE THREAD

**Issue by elray1** [reichlab/abc-model-selection#3]
- Handle regions in `load_who_nrevss`
 - Handle regions in `load_ilinet`
 - Make some exploratory plots to show what's going on at the regional level. Are trends in what strains are circulating substantively different in different regions?

**Comment by donga0223** [comment]
- `ilinet data` no strains variable

**Comment by donga0223** [comment]
Done! Please check it [here](https://github.com/reichlab/abc-model-selection/blob/main/code/eda/eda_hhs.ipynb) 

During the period 1997/98 - 1999/00, 2001/02, 2004/05, etc., it can be seen that the a_h3 strain shows regional differences. In periods when a_h1 was dominant, such as 2008/09, 2009/10, and 2019/20, there are a difference between regions of the a_h1 strain.
